apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
          }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            except eks.amazonaws.com emr-containers.amazonaws.com
        }
        forward eks.amazonaws.com 1.1.1.1
        forward emr-containers.amazonaws.com 1.1.1.1
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2025-02-13T06:00:50Z"
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
  resourceVersion: "724"
  uid: 0758ea99-4fe9-43ed-ab79-26182d1fd220
